# Generated by Django 6.0.7 on 2026-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this registration has been approved by admin.'),
        ),
    ]
