# Generated by Django 6.0.7 on 2026-07-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassadorprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ambassadorprofile',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambassadorprofile',
            name='institution',
            field=models.CharField(max_length=200),
        ),
    ]
